apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
  - image: pokerImage
    context: .
    docker:
      # noCache: true
      dockerfile: build/package/Dockerfile
      # buildArgs:
      #   script: clients.sh
    sync:
      auto: true
  - image: groomImage
    context: .
    docker:
      # noCache: true
      dockerfile: build/package/groom/Dockerfile
    sync:
      auto: true
  local:
    concurrency: 2
    push: false
deploy:
  helm:
    # flags: 
    #   upgrade: 
    #     - '--dry-run'
    #   install: 
    #     - '--dry-run'
    releases:
    - name: poker
      chartPath: deployments/poker
      # skipBuildDependencies: true
      valuesFiles:
      - deployments/poker/values-debug.yaml
      setValueTemplates:
        image.repository: "{{.IMAGE_REPO_pokerImage}}"
        image.tag: "{{.IMAGE_TAG_pokerImage}}@{{.IMAGE_DIGEST_pokerImage}}"
        imagegroom.repository: "{{.IMAGE_REPO_groomImage}}"
        imagegroom.tag: "{{.IMAGE_TAG_groomImage}}@{{.IMAGE_DIGEST_groomImage}}"
      setValues:
        containerPort: 8083