apiVersion: skaffold/v4beta2
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: pokerImage
    context: .
    docker:
      noCache: true
      dockerfile: build/package/Dockerfile
    sync:
      auto: true
  local:
    concurrency: 0
    push: false
    # tryImportMissing: true # saves time with cache
deploy:
  kubeContext: minikube
  helm:
    # flags: 
    #   upgrade: 
    #     - '--dry-run'
    #   install: 
    #     - '--dry-run'
    releases:
    - name: poker
      chartPath: deployments/poker
      skipBuildDependencies: true
      valuesFiles:
      - deployments/poker/values.yaml
      setValueTemplates:
        image.repository: "{{.IMAGE_REPO_pokerImage}}"
        image.tag: "{{.IMAGE_TAG_pokerImage}}@{{.IMAGE_DIGEST_pokerImage}}"
        imagegroom.repository: "{{.IMAGE_REPO_pokerImage}}"
        imagegroom.tag: "{{.IMAGE_TAG_pokerImage}}@{{.IMAGE_DIGEST_pokerImage}}"
      setValues:
        containerPort: 8083
profiles:
  - name: dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: build/package/debug/Dockerfile
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles/0
        value: deployments/debug/values-debug.yaml