{{- range $index, $room := .Values.rooms }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: room-{{ $room | lower }}-app
  name: room-{{ $room | lower }}
  namespace: poker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-{{ $room | lower }}-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: room-{{ $room | lower }}-app
    spec:
      serviceAccountName: groom-sa
      containers:
        - image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          name: room
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ $.Values.tty2webPort | add $index }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          tty: true # this is required for tty2web to work
          ports:
            - protocol: "TCP"
              name: {{ $room | lower }}-port
              containerPort: {{ $.Values.tty2webPort | add $index }}
          # add debug config if needed
          {{ if $.Values.debugPoker }}
            - protocol: "TCP"
              name: debugp-{{ $room | lower }}
              containerPort: {{ $.Values.debugPokerPort }}
          workingDir: /go/src
          command: [ "/dlv" ]
          args: [ "debug", "/go/src/cmd", "--headless", "--listen=:{{ $.Values.debugPokerPort }}", "--api-version=2", "--", "client", "-websocket", "localhost:8080" ]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          resources:
            requests:
              cpu: 50m
              memory: 2000Mi
            limits:
              cpu: 4
              memory: 2000Mi
          volumeMounts:
            - mountPath: "/go/src"
              name: go-volume
      volumes:
        - name: go-volume
          persistentVolumeClaim:
            claimName: go-pvc
          {{ else }}
          command: [ "./clients.sh" ]
          args: [ "{{ $.Values.tty2webPort | add $index }}", "{{ $room }}" ]
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 500m
              memory: 50Mi
          securityContext:
            # capabilities:
            #   drop:
            #     - all
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          # automountServiceAccountToker: false
          {{ end }}    
---
{{- end }}    