{{- range $index, $room := .Values.rooms }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: room-{{ $room.name | lower }}-app
  name: room-{{ $room.name | lower }}
  namespace: poker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room-{{ $room.name | lower }}-app
  strategy: {}
  template:
    metadata:
      annotations:
        checksum/config: {{ print $room | sha256sum }} # avoid pod restart when a room is removed
      labels:
        app: room-{{ $room.name | lower }}-app
    spec:
      serviceAccountName: groom-sa
      containers:
        - image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          name: room
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          tty: true # this is required for tty2web to work
          ports:
            - protocol: "TCP"
              name: {{ $room.name | lower }}-port
              containerPort: {{ $.Values.tty2webPort | add $room.index }}
          # add debug config if needed
          {{ if $.Values.debugPoker }}
            - protocol: "TCP"
              name: debugp-{{ $room.name | lower }}
              containerPort: {{ $.Values.debugPokerPort }}
          workingDir: /go/src
          # make container sleep, use kubectl exec to start debuger later
          # then in /go/src # /clients-debug.sh 9229
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            privileged: true
          resources:
            requests:
              cpu: 1
              memory: 2000Mi
            limits:
              cpu: 4
              memory: 2000Mi
          volumeMounts:
            - mountPath: "/go/src"
              name: go-volume
      volumes:
        - name: go-volume
          persistentVolumeClaim:
            claimName: go-pvc
          {{ else }}
          command: [ "./clients.sh" ]
          args: [ "{{ $.Values.tty2webPort | add $room.index }}", "{{ $room.name }}" ]
          resources:
            requests:
              cpu: 500m
              memory: 200Mi
            limits:
              cpu: 2
              memory: 200Mi
          securityContext:
            # capabilities:
            #   drop:
            #     - all
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          # automountServiceAccountToker: false
          readinessProbe:
            httpGet:
              path: /
              port: {{ $.Values.tty2webPort | add $room.index }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          {{ end }}    
---
{{- end }}