apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: groom-app
  name: groom
  namespace: poker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groom-app
  template:
    metadata:
      labels:
        app: groom-app
    spec:
      serviceAccountName: groom-sa
      volumes:
        - name: go-volume
          persistentVolumeClaim:
            claimName: go-pvc
      containers:
        - image: {{ .Values.imagegroom.repository }}:{{ .Values.imagegroom.tag }}
          imagePullPolicy: {{ .Values.imagegroom.pullPolicy }}
          name: groom
          # add debug config if needed
          {{ if .Values.debug }}
          ports: 
            - name: groom-port
              protocol: "TCP"
              containerPort: {{ .Values.debugPort }}
          workingDir: /go/src
          command: [ "/dlv" ]
          args: [ "debug", "/go/src/cmd/groom", "--headless", "--listen=:{{ .Values.debugPort }}", "--api-version=2" ]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          # otherwise applyse security
          {{ else }}
          securityContext:
            capabilities:
              drop:
                - all
            runAsUser: 0
            runAsGroup: 0
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          automountServiceAccountToken: false
          {{ end }}
          resources:
            requests:
              cpu: 50m
              memory: 2000Mi
            limits:
              cpu: 4
              memory: 2000Mi
          volumeMounts:
            - mountPath: "/go/src"
              name: go-volume