apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: groom-app
  name: groom
  namespace: poker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groom-app
  template:
    metadata:
      labels:
        app: groom-app
    spec:
      # serviceAccountName: poker-sa
      containers:
        - image: {{ .Values.imagegroom.repository }}:{{ .Values.imagegroom.tag}}
          imagePullPolicy: {{ .Values.imagegroom.pullPolicy }}
          name: groom
          # for Run without debug config add debug port
          ports: 
            - name: groom-port
              protocol: "TCP"
              containerPort: 9229
          command: ["/dlv"]
          args: [ "exec", "/groom", "--headless", "--continue", "--accept-multiclient", "--listen=:9229", "--api-version=2" ]
          # securityContext:
            # capabilities:
            #   drop:
            #     - all
            # runAsUser: 1234
            # runAsGroup: 1234
            # readOnlyRootFilesystem: true
            # allowPrivilegeEscalation: false
          # automountServiceAccountToken: false
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              cpu: 4
              memory: 200Mi