apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: groom-app
  name: groom
  namespace: poker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groom-app
  template:
    metadata:
      labels:
        app: groom-app
    spec:
      serviceAccountName: groom-sa
      # add debug config if needed
      {{ if .Values.debugGroom }}
      volumes:
        - name: go-volume
          persistentVolumeClaim:
            claimName: go-pvc
      {{ end }}
      containers:
        - image: {{ .Values.imagegroom.repository }}:{{ .Values.imagegroom.tag }}
          imagePullPolicy: {{ .Values.imagegroom.pullPolicy }}
          name: groom
          tty: true # this is required for tty2web to work
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.groomPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          ports: 
            - protocol: "TCP"
              name: groom-port
              containerPort: {{ .Values.groomPort }}
          # add debug config if needed
          {{ if .Values.debugGroom }}
            - name: debug-groomp
              protocol: "TCP"
              containerPort: {{ .Values.debugGroomPort }}
          workingDir: /go/src
          command: [ "/dlv" ]
          args: [ "debug", "/go/src/cmd/groom", "--headless", "--listen=:{{ .Values.debugGroomPort }}", "--api-version=2", "--", "http://{{ .Values.externalDomain }}" ]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          resources:
            requests:
              cpu: 50m
              memory: 2000Mi
            limits:
              cpu: 4
              memory: 2000Mi
          volumeMounts:
            - mountPath: "/go/src"
              name: go-volume
          # otherwise apply security
          {{ else }}
          command: [ "/groom-clients.sh" ]
          args: [ "{{ .Values.groomPort }}" ]
          securityContext:
            # capabilities:
            #   drop:
            #     - all
            # readOnlyRootFilesystem: true
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
          # automountServiceAccountToken: false
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 50Mi
          {{ end }}