apiVersion: v1
kind: ServiceAccount
metadata:
  name: groom-sa
  namespace: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: readsecret
  namespace: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - pods
  - configmaps
  - services
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: groomrb
  namespace: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: readsecret
subjects:
- kind: ServiceAccount
  name: groom-sa
  namespace: {{ .Release.Name }}