{{- range $index, $room := .Values.rooms }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: room-{{ $room.name | lower }}-app
  name: room-{{ $room.name | lower }}
  namespace: poker
spec:
  ports:
{{ if $.Values.debugPoker }}
  - port: {{ $.Values.debugPokerPort | add $room.index }}
    name: debugp-{{ $room.name | lower }}
    protocol: TCP
    targetPort: {{ $.Values.debugPokerPort | add $room.index }}
{{ end }}
  - port: {{ $.Values.tty2webPort | add $room.index }}
    name: {{ $room.name | lower }}
    protocol: TCP
    targetPort: {{ $.Values.tty2webPort | add $room.index }}
  selector:
    app: room-{{ $room.name | lower }}-app
---
{{- end }}    
# expose debug port if needed
apiVersion: v1
kind: Service
metadata:
  labels:
    app: groom-app
  name: groom  
  namespace: poker
spec:
  ports:
{{ if .Values.debugGroom }}
  - port: {{ .Values.debugGroomPort }}
    name: debug-groom
    protocol: TCP
    targetPort: {{ .Values.debugGroomPort }}
{{ end }}
  - port: {{ .Values.groomPort }}
    name: groom-port
    protocol: TCP
    targetPort: {{ .Values.groomPort }}
  selector:
    app: groom-app