{{- range $index, $room := .Values.rooms }}
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: room-{{ $room | lower }}-app
    app.kubernetes.io/managed-by: Helm
  name: room-{{ $room | lower }}
  namespace: poker
spec:
  ports:
  - port: {{ $.Values.tty2webPort | add $index }}
    protocol: TCP
    targetPort: {{ $.Values.tty2webPort | add $index }}
  selector:
    app: room-{{ $room | lower }}-app
status:
  loadBalancer: {}
---
{{- end }}    
