rooms: # room name one word
  - TeamRed
  - TeamBlue
  - TeamYellow
tty2webPort: 8083
image: 
  repository: ghcr.io/fc92/poker
  tag: main
  pullPolicy: IfNotPresent # default PullPolicy
imagegroom:
  repository: ghcr.io/fc92/poker
  tag: main
  pullPolicy: IfNotPresent # default PullPolicy
externalDomain: poker.local # UPDATE required for target domain
groomPort: 38888
