rooms: # room name one word
  - TeamRed
  - TeamBlue
  - Yellow
tty2webPort: 8083
image:
  repository: harbor.lab.dev/poker/poker # default repo
  tag: latest # default tag 
  pullPolicy: IfNotPresent # default PullPolicy
imagegroom:
  repository: harbor.lab.dev/poker/poker # default repo
  tag: latest # default tag 
  pullPolicy: IfNotPresent # default PullPolicy
externalDomain: poker.local # UPDATE required for target domain
debugPoker: true
debugGroom: false
debugPokerPort: 9229
debugGroomPort: 8229
groomPort: 38888
